### ISSUE TITLE
Сборка блока датчиков расстояния

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#10]
**Задача:** собрать полностью рабочий блок датчика расстояния. Подключить все ИК-датчики к плате, закрепить на корпусе, разработанном в задачах #7 и #3.

**На выходе получить:** блок датчика расстояния для закрепления на корпусе танка.

**Tasklist:**
- [x] разместить ИК-датчики в корпусе датчика расстояния.
- [x] подключить датчики к плате
- [x] проверить датчики на работоспособность
- [x] закрепить блок датчика расстояния на корпусе танка
- [x] Процесс задокументировать в формате фото/видео

**Comment by danilchican** [comment]
Чтобы разблокировать данную таску, нужно создать issue с описанием изготовления платы. За это отвечает @YuraStr и @MikhailLU.

**Comment by danilchican** [comment]
Task'a разблокирована. issue #15.

**Comment by Lipotam** [comment]
Выполнение доступно после завершения задач #7 и #15
