### ISSUE TITLE
Cоздание 3D-модели корпуса блока датчика линии

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#11]
**Задача:** разработать корпус для датчиков линии для удобного размещения его на корпусе танка (#2).

**На выходе получить:** 3D-модель формата .max (для последующего моделирования), .stl (для печати на 3D-принтере) 

**Tasklist:**
- [ ] Определить оптимальное положение, угол поворота датчиков
- [ ] Определить местоположение блока с датчиками
- [ ] Определить размеры корпуса 
- [ ] Нарисовать модель корпуса в 3Ds Max

**Comment by Lipotam** [comment]
После обсуждения принятно решение отложить задачу
