### ISSUE TITLE
Распечатать на 3D-принтере модель корпуса блока датчика линии

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#12]
**Задача:** Распечатать на 3D-принтере модель корпуса датчика линии, проектирование которого велось в задаче #11.

**На выходе получить:** распечатанную пластиковую модель.

- [ ] Получить модель формата .max
- [ ] Разрезать эту модель на слои в Slic3r
- [ ] Получить модель формата .stl для печати
- [ ] Распечатать модель на 3D-принтере
- [ ] Процесс и результат запечатлеть в виде фото/видео
- [ ] Проверить модель на дефекты

**Comment by Lipotam** [comment]
Выполнение доступно после завершения задачи #11

**Comment by danilchican** [comment]
Принято решение отложить.
