### ISSUE TITLE
Расположить корпус датчика линии внизу на корпусе танка.

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#13]
**Задача:** расположить распечатанный пластиковый корпус датчика линии, разработанный в задачах #11 и #12, внизу на корпусе танка.

**На выходе получить:** корпус танка вместе с закрепленным с помощью крепежных деталей датчиком линии.

**Tasklist:**
- [x] Закрепить корпус датчика линии на корпусе танка с помощью крепежных деталей
- [x] Соединить электрически датчик линии с микроконтроллером.
- [x] Задокументировать процесс в виде фото/видео.

**Comment by Lipotam** [comment]
Выполнение доступно после завершения задач #12 и #17
