### ISSUE TITLE
Сборка датчика линии

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#14]
**Задача:** собрать полностью рабочий блок датчика линии. Подключить все ИК-датчики к плате, закрепить на корпусе, разработанном в задачах #11 и #13.

**На выходе получить:** блок датчика линии для закрепления на корпусе танка.

**Tasklist:**
- [x] разместить ИК-датчики в корпусе датчика расстояния.
- [x] подключить датчики к плате
- [x] проверить датчики на работоспособность
- [x] закрепить блок датчика линии на корпусе танка
- [x] Процесс задокументировать в формате фото/видео

**Примечание:** Чтобы разблокировать данную таску, нужно создать issue с описанием процесса изготовления платы. За это отвечает @YuraStr и @MikhailLU.

**Comment by Lipotam** [comment]
Выполнение доступно после завершения задач #12 и #17

**Comment by danilchican** [comment]
Отложено по решению.
