### ISSUE TITLE
Крепление поворотной платформы с камерой на верхней части шасси.

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#16]
**Задача:** закрепить поворотную платформу с камерой на верхней части шасси.
**На выходе получить:** шасси с закрепленной платформой.

**Tasklist:** 

- [x] Собрать поворотную платформу
- [x] Определиться с местоположением поворотной платформы на верхней части шасси
- [x] Закрепить поворотную платформу на выбранной области шасси.

**Comment by Lipotam** [comment]
Рекомендую выполнять задачу после того, как расположение всех элементов будет смоделированно на компьютерной модели
