### ISSUE TITLE
Добавление мультиплексора и декодера в Sprint Layout

### ISSUE THREAD

**Issue by Alexpechonov** [danilchican/trackPlatform#22]
**Задача:** В программу Sprint Layout добавить схемы декодера и мультиплексора.
**На выходе получить:** Схемы для проектирования плат.

**Comment by Lipotam** [comment]
Чем заблокирована?

**Comment by Alexpechonov** [comment]
Выполнение доступно после завершения задачи #21

**Comment by Alexpechonov** [comment]
Используются корпуса SOIC-16
