### ISSUE TITLE
Проектирование схемы адресации блока датчиков линии

### ISSUE THREAD

**Issue by Alexpechonov** [danilchican/trackPlatform#23]
**Задача:** спроектировать плату адресации блока датчиков линии.
**На выходе получить:** схему, по которой можно изготовить плату.

**Comment by Lipotam** [comment]
Чем заблокирована?

**Comment by Alexpechonov** [comment]
Выполнение доступно после завершения задачи #22

**Comment by Alexpechonov** [comment]
Файл Схемы/Датчики линии.lay на дропбоксе
