### ISSUE TITLE
Cоздание 3D-модели корпуса блока датчиков расстояния

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#3]
**Задача:** разработать корпус для лазерных датчиков для удобного размещения его на корпусе танка (#2) с передней стороны.

**На выходе получить:** 3D-модель формата .max (для последующего моделирования), .stl (для печати на 3D-принтере) 

**Tasklist:**
- [x] Определить оптимальное положение, угол поворота датчиков
- [x] Определить местоположение блока с датчиками
- [x] Определить размеры корпуса 
- [x] Нарисовать модель корпуса в 3Ds Max

**Comment by Lipotam** [comment]
Конфигурация корпуса должна предусматривать защиту ИК-датчиков от повреждения при наезде на препятствие
