### ISSUE TITLE
Распечатать на 3D-принтере модель корпуса блока датчиков расстояния

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#7]
**Задача:** Распечатать на 3D-принтере модель корпуса датчика расстояния, проектирование которого велось в задаче #3.

**На выходе получить:** распечатанную пластиковую модель.

- [x] Получить модель формата .max
- [x] Разрезать эту модель на слои в Slic3r
- [x] Получить модель формата .stl для печати
- [x] Распечатать модель на 3D-принтере
- [x] Процесс и результат запечатлеть в виде фото/видео
- [x] Проверить модель на дефекты

**Comment by Lipotam** [comment]
Выполнение доступно после завершения задачи #3
