### ISSUE TITLE
Проектирование схемы адресации блока датчиков расстояния

### ISSUE THREAD

**Issue by Alexpechonov** [danilchican/trackPlatform#8]
**Задача:** В программе Sprint Layout спроектировать схему адресации датчика расстояния.
**На выходе получить:** Схему для дальнейшей распечатки.

**Comment by Lipotam** [comment]
Чем заблокирована ?

**Comment by Alexpechonov** [comment]
Выполнение доступно после завершения задачи #20

**Comment by Alexpechonov** [comment]
Файл Схемы/Датчики линии.lay на дропбоксе
