### ISSUE TITLE
Расположить корпус блока датчиков расстояния на корпусе танка (спереди).

### ISSUE THREAD

**Issue by danilchican** [danilchican/trackPlatform#9]
**Задача:** расположить распечатанный пластиковый корпус датчика расстояния, разработанный в задачах #3 и #7, спереди на корпусе танка.

**На выходе получить:** корпус танка вместе с закрепленным с помощью крепежных деталей датчиком расстояния.

**Tasklist:**
- [x] Закрепить корпус датчика расстояния на корпусе танка с помощью крепежных деталей
- [x] Соединить электрически датчик расстояния с микроконтроллером.
- [x] Задокументировать процесс в виде фото/видео.

**Comment by Lipotam** [comment]
Выполнение невозможно, пока не будет завершена задача #10
